#!/usr/bin/env bash
# Regenerates single/lulesh.hpp and single/lulesh.cpp from the upstream-unchanged
# sources one directory up. The single-file build is a concatenation, nothing in the
# physics changes: the only edits are dropping the intra-project #include lines, the
# dead `#if USE_MPI` include blocks and the silo body of lulesh-viz.cc, fixing the
# backend to FMI in the header, and moving the LLNL license block to the top.
set -euo pipefail
R=$(cd "$(dirname "$0")/.." && pwd)
OUT=$(cd "$(dirname "$0")" && pwd)

# Seams this script relies on; fail loudly if the sources drift.
[ "$(sed -n 145p "$R/lulesh.cc")" = '*/' ]          || { echo "lulesh.cc: license block no longer ends at line 145" >&2; exit 1; }
[ "$(sed -n 18p "$R/lulesh.h")" = '#if USE_MPI' ]   || { echo "lulesh.h: backend-selection block moved" >&2; exit 1; }
[ "$(sed -n 22p "$R/lulesh.h")" = '#endif' ]        || { echo "lulesh.h: backend-selection block moved" >&2; exit 1; }
[ "$(sed -n 423p "$R/lulesh-viz.cc")" = '#else' ]   || { echo "lulesh-viz.cc: non-silo stub moved" >&2; exit 1; }
[ "$(sed -n 432p "$R/lulesh-viz.cc")" = '#endif' ]  || { echo "lulesh-viz.cc: non-silo stub moved" >&2; exit 1; }

# Filters (stdin -> stdout).
strip_local_includes() { sed -E '/^[[:space:]]*#[[:space:]]*include[[:space:]]*"(lulesh\.h|lulesh-fmi\.h)"/d'; }
strip_mpi_include()    { perl -0pe 's/#if USE_MPI\n#\s*include <mpi\.h>\n#endif\n//g'; }
section()              { printf '\n// ===================== from %s =====================\n\n' "$1"; }

# ---------------------------------------------------------------- lulesh.hpp
{
cat <<'EOF'
// lulesh.hpp -- declarations for the single-file LULESH 2.0 on FMI (see lulesh.cpp).
//
// GENERATED by single/generate.sh from ../lulesh-fmi.h and ../lulesh.h. Do not edit;
// edit the sources and regenerate. The one change from the sources is that the
// communication backend is fixed to FMI here instead of chosen on the compile line.
#ifndef LULESH_SINGLE_HPP
#define LULESH_SINGLE_HPP

#define USE_MPI 0
#define USE_FMI 1
#define USE_DISTRIBUTED 1

// ---------------------------------------------------------------------------
// From lulesh-fmi.h: the MPI subset LULESH uses, implemented over FMI in lulesh.cpp
// ---------------------------------------------------------------------------
EOF
sed -e '/^#ifndef LULESH_FMI_H$/d' -e '/^#define LULESH_FMI_H$/d' -e '/^#endif \/\/ LULESH_FMI_H$/d' "$R/lulesh-fmi.h"
cat <<'EOF'

// ---------------------------------------------------------------------------
// From lulesh.h (lines 1-22, the backend-selection block, replaced by the defines above)
// ---------------------------------------------------------------------------
EOF
sed -n '23,$p' "$R/lulesh.h"
echo
echo '#endif // LULESH_SINGLE_HPP'
} > "$OUT/lulesh.hpp"

# ---------------------------------------------------------------- lulesh.cpp
{
sed -n '1,145p' "$R/lulesh.cc"
cat <<'EOF'

// ===========================================================================
// Single-file LULESH 2.0 on FMI.
//
// GENERATED by single/generate.sh: a concatenation of the upstream-unchanged LULESH
// sources one directory up (lulesh-init.cc, lulesh-util.cc, lulesh-comm.cc, lulesh.cc
// and the non-silo stub of lulesh-viz.cc) with the MPI-compatible shim (lulesh-fmi.cc)
// that implements the MPI subset declared in lulesh.hpp on one FMI::Communicator.
// LULESH still calls MPI_*; nothing in the physics knows about FMI.
//
// Build: c++ -std=c++17 -O3 -DNDEBUG -I<fmi>/include lulesh.cpp -o lulesh2.0 <libFMI and its deps>
//        (or the lulesh2.0-single CMake target in the parent directory, -DWITH_FMI=ON)
// Run:   one process per rank with FMI_RANK, FMI_WORLD_SIZE, FMI_CONFIG, FMI_COMM_NAME in
//        the environment and the simulation options on argv, e.g. -s 30 -i 9999999 -p.
//        Rank count must be a perfect cube. Rank 0 prints "Final Origin Energy".
// ===========================================================================

#include "lulesh.hpp"
EOF
section lulesh-fmi.cc;  strip_local_includes < "$R/lulesh-fmi.cc"
section lulesh-init.cc; strip_local_includes < "$R/lulesh-init.cc" | strip_mpi_include
section lulesh-util.cc; strip_local_includes < "$R/lulesh-util.cc" | strip_mpi_include
section lulesh-comm.cc; strip_local_includes < "$R/lulesh-comm.cc"
section "lulesh-viz.cc (non-silo stub only)"; sed -n '424,431p' "$R/lulesh-viz.cc"
section "lulesh.cc (license block moved to the top of this file)"
sed -n '146,$p' "$R/lulesh.cc" | strip_local_includes
} > "$OUT/lulesh.cpp"

grep -q 'DumpToVisit' "$OUT/lulesh.cpp" || { echo "viz stub missing" >&2; exit 1; }
! grep -qE "#include \"(lulesh\.h|lulesh-fmi\.h)\"" "$OUT/lulesh.cpp" "$OUT/lulesh.hpp" || { echo "local include survived" >&2; exit 1; }
echo "wrote $OUT/lulesh.hpp ($(wc -l < "$OUT/lulesh.hpp") lines) and $OUT/lulesh.cpp ($(wc -l < "$OUT/lulesh.cpp") lines)"
